ci : Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,10 +1,3 @@
-# This workflow uses actions that are not certified by GitHub.
-# They are provided by a third-party and are governed by
-# separate terms of service, privacy policy, and support
-# documentation.
-# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle
-
 name: JAVA CI with Gradle
 
 on:
@@ -18,7 +11,8 @@ jobs:
       contents: read
 
     steps:
-    - uses: actions/checkout@v4
+    - name: Checkout code
+      uses: actions/checkout@v4
 
     - name: Set up JDK 17
       uses: actions/setup-java@v4
@@ -26,7 +20,7 @@ jobs:
         java-version: '17'
         distribution: 'temurin'
 
-    - name: Make application-secret.yml
+    - name: Create application-secret.yml
       run: |
         mkdir -p ./src/main/resources
         echo "${{ secrets.APPLICATION_SECRET }}" > ./src/main/resources/application-secret.yml
@@ -47,9 +41,9 @@ jobs:
       run: |
         COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7 | tr '[:upper:]' '[:lower:]' | tr -dc 'a-z0-9')
         echo "Commit SHA: $COMMIT_SHA"
-        
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA .
 
+        docker build -t ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA .
+        
         docker push ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA
         
         docker tag ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:latest
@@ -66,16 +60,26 @@ jobs:
           COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7 | tr '[:upper:]' '[:lower:]' | tr -dc 'a-z0-9')
           echo "COMMIT_SHA: $COMMIT_SHA"
           echo "Pulling Docker image on server..."
-          docker pull ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA || { echo "Failed to pull image"; exit 1; }
+          if ! docker pull ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA; then
+            echo "Failed to pull image"; exit 1;
+          fi
 
           echo "Stopping existing container..."
           if docker ps -q --filter "name=yellow-ribbon" | grep -q .; then
-            docker stop yellow-ribbon || { echo "Failed to stop container"; exit 1; }
-            docker rm yellow-ribbon || { echo "Failed to remove container"; exit 1; }
+            if ! docker stop yellow-ribbon; then
+              echo "Failed to stop container"; exit 1;
+            fi
+            if ! docker rm yellow-ribbon; then
+              echo "Failed to remove container"; exit 1;
+            fi
           fi
 
           echo "Running new container..."
-          docker run -d --name yellow-ribbon --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA || { echo "Failed to start container"; exit 1; }
+          if ! docker run -d --name yellow-ribbon --log-driver=syslog -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/yellow-ribbon:$COMMIT_SHA; then
+            echo "Failed to start container"; exit 1;
+          fi
 
           echo "Cleaning up unused images..."
-          docker image prune -a -f || { echo "Failed to clean up images"; exit 1; }
+          if ! docker image prune -a -f; then
+            echo "Failed to clean up images"; exit 1;
+          fi
